version: '3.8'

services:
  db:
    image: 'postgres:15'
    container_name: postgres${APP_NAME}
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - .docker/postgresql:/var/lib/postgresql/
    networks:
      - app-network
  redis:
    image: redis:alpine
    container_name: redis_${APP_NAME}
    ports:
      - '6379:6379'
    volumes:
      - .docker/data-redis:/data
    networks:
      - app-network
  minio:
    image: bitnami/minio:latest
    container_name: minio_${APP_NAME}
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - app-network
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    volumes:
      - .docker/minio-data:/data # Volume for Minio data
networks:
  app-network:
    driver: bridge
