version: "3.8"

services:
  db:
    image: "postgres:15"
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      PGPASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
      - .docker/data/db:/var/lib/postgresql/data
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
